name = "MirrorUpdater"
uuid = "7f0fc4bf-4ffe-4e21-ab91-7bf1358d5ab3"
authors = ["Dilum Aluthge <dilum@aluthge.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
ArgParse = "^0.6.1"
Conda = "^1.1.1"
Coverage = "^0.6.0"
GitHub = "^5.0.2"
HTTP = "^0.7.1"
JSON = "^0.19.0"
TimeZones = "^0.8.0"
julia = "^1.1.0"
